### ISSUE TITLE
Multiple, unrelated changes in one session

### ISSUE THREAD

**Issue by blawnode** [womri1998/Wordle#10]
If I have multiple changes I've made in one go, and they all clearly belong in different commits,
I should go through the trouble of separating my changes into separate commits, right?

**Comment by womri1998** [comment]
It depends on how big the changes are. If each of them has a big impact on the project, preferably yes, you should seperate them.
If one of the changes is not too big, just finish both changes and commit together.
But yes, optimally it should not happen, the branches and commits should be clear and for single purpose at a time.

**Comment by blawnode** [comment]
Alrighty, that answers it.
I got one big change unrelated to the core, with a few tiny changes related to the core.
Might as well go through the trouble of doing the separation,.
